In [ ]:
import numpy as np
a=np.array([[(1,2,3),(4,5,6)]])
b=np.array([[(1,2,3),(4,5,6)]])
c=np.array([[1,2,3],[4,5,6]])


In [12]:
np.subtract(a,b)


array([[[0, 0, 0],
        [0, 0, 0]]])

In [13]:
np.equal(a,b)

array([[[ True,  True,  True],
        [ True,  True,  True]]])

In [14]:
a.sort()

In [21]:
np.transpose(c)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.ravel(a)


array([1, 2, 3, 4, 5, 6])

In [25]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [26]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
import random

In [35]:
arr=np.random.rand(4,5)*100
arr.sort()
print(arr)

[[ 3.09346925 23.52507105 44.32328968 54.5447977  71.74012828]
 [25.35810329 36.39451435 49.21321166 90.12054134 98.84333825]
 [ 3.47952438 26.00710326 57.67041438 77.09902025 78.94272111]
 [12.45832714 32.89268566 77.79626975 85.78467301 99.09839399]]


In [32]:
arr.sort()
print(arr)

[[46.90382275 51.9262085  71.21403493 71.95450462 84.51523279]
 [ 5.17341061 11.72067399 24.7588502  52.8773783  78.66721706]
 [15.17712137 16.13498764 23.97716735 32.4341028  42.66979873]
 [14.47890336 50.51149689 79.17426084 87.86908071 94.02501171]]


In [41]:
d=np.array([[1,2,3],[4,5,6]])
d.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
d.flatten()

array([1, 2, 3, 4, 5, 6])

In [45]:
np.append(d,[7,8,9])
print(d)


[[1 2 3]
 [4 5 6]]
